(function(d){var a=function(a){d(d.address).trigger(d.extend(d.Event(a),function(){for(var a={},b=d.address.parameterNames(),j=0,c=b.length;j<c;j++)a[b[j]]=d.address.parameter(b[j]);return{value:d.address.value(),path:d.address.path(),pathNames:d.address.pathNames(),parameterNames:b,parameters:a,queryString:d.address.queryString()}}.call(d.address)))},b=function(){d().bind.apply(d(d.address),Array.prototype.slice.call(arguments));return d.address},e=function(){return P.pushState&&k.state!==q},c=function(){return("/"+
r.pathname.replace(RegExp(k.state),"")+r.search+(f()?"#"+f():"")).replace(T,"/")},f=function(){var a=r.href.indexOf("#");return-1!=a?g(r.href.substr(a+1),x):""},h=function(){return e()?c():f()},m=function(a){a=a.toString();return(k.strict&&"/"!=a.substr(0,1)?"/":"")+a},g=function(a,b){return k.crawlable&&b?(""!==a?"!":"")+a:a.replace(/^\!/,"")},j=function(a,b){return parseInt(a.css(b),10)},l=function(a){for(var b,j,c=0,d=a.childNodes.length;c<d;c++){try{"src"in a.childNodes[c]&&a.childNodes[c].src&&
(b=String(a.childNodes[c].src))}catch(e){}if(j=l(a.childNodes[c]))b=j}return b},n=function(){if(!N){var a=h();u!=a&&(G&&7>D?r.reload():(G&&8>D&&k.history&&E(C,50),u=a,F(x)))}},F=function(b){a(U);a(b?V:W);E(z,10)},z=function(){if("null"!==k.tracker&&null!==k.tracker){var a=d.isFunction(k.tracker)?k.tracker:v[k.tracker],b=(r.pathname+r.search+(d.address&&!e()?d.address.value():"")).replace(/\/\//,"/").replace(/^\/$/,"");d.isFunction(a)?a(b):d.isFunction(v.urchinTracker)?v.urchinTracker(b):v.pageTracker!==
q&&d.isFunction(v.pageTracker._trackPageview)?v.pageTracker._trackPageview(b):v._gaq!==q&&d.isFunction(v._gaq.push)&&v._gaq.push(["_trackPageview",decodeURI(b)])}},C=function(){var a="javascript:"+x+";document.open();document.writeln('<html><head><title>"+A.title.replace("'","\\'")+"</title><script>var "+J+' = "'+encodeURIComponent(h())+(A.domain!=r.hostname?'";document.domain="'+A.domain:"")+"\";\x3c/script></head></html>');document.close();";7>D?y.src=a:y.contentWindow.location.replace(a)},t=function(){if(K&&
-1!=X){var a,b=K.substr(X+1).split("&");for(i=0;i<b.length;i++)a=b[i].split("="),/^(autoUpdate|crawlable|history|strict|wrap)$/.test(a[0])&&(k[a[0]]=isNaN(a[1])?/^(true|yes)$/i.test(a[1]):0!==parseInt(a[1],10)),/^(state|tracker)$/.test(a[0])&&(k[a[0]]=a[1]);K=null}u=h()},p=function(){if(!Y){Y=B;t();var b=function(){var a,b=d("a"),c=b.size(),j=-1,e=function(){++j!=c&&(a=d(b.get(j)),a.is('[rel*="address:"]')&&a.address(),E(e,1))};E(e,1);if(k.crawlable){var g=r.pathname.replace(/\/$/,"");-1!=d("body").html().indexOf("_escaped_fragment_")&&
d('a[href]:not([href^=http]), a[href*="'+document.domain+'"]').each(function(){var a=d(this).attr("href").replace(/^http:/,"").replace(RegExp(g+"/?$"),"");(""===a||-1!=a.indexOf("_escaped_fragment_"))&&d(this).attr("href","#"+a.replace(/\/(.*)\?_escaped_fragment_=(.*)$/,"!$2"))})}},c=d("body").ajaxComplete(b);b();k.wrap&&(d("body > *").wrapAll('<div style="padding:'+(j(c,"marginTop")+j(c,"paddingTop"))+"px "+(j(c,"marginRight")+j(c,"paddingRight"))+"px "+(j(c,"marginBottom")+j(c,"paddingBottom"))+
"px "+(j(c,"marginLeft")+j(c,"paddingLeft"))+'px;" />').parent().wrap('<div id="'+J+'" style="height:100%;overflow:auto;position:relative;'+(L&&!window.statusbar.visible?"resize:both;":"")+'" />'),d("html, body").css({height:"100%",margin:0,padding:0,overflow:"hidden"}),L&&d('<style type="text/css" />').appendTo("head").text("#"+J+"::-webkit-resizer { background-color: #fff; }"));G&&8>D&&(b=A.getElementsByTagName("frameset")[0],y=A.createElement((b?"":"i")+"frame"),b?(b.insertAdjacentElement("beforeEnd",
y),b[b.cols?"cols":"rows"]+=",0",y.noResize=B,y.frameBorder=y.frameSpacing=0):(y.style.display="none",y.style.width=y.style.height=0,y.tabIndex=-1,A.body.insertAdjacentElement("afterBegin",y)),E(function(){d(y).bind("load",function(){var a=y.contentWindow;u=a[J]!==q?a[J]:"";u!=h()&&(F(x),r.hash=g(u,B))});y.contentWindow[J]===q&&C()},50));E(function(){a("init");F(x)},1);e()||(G&&7<D||!G&&"on"+M in v?v.addEventListener?v.addEventListener(M,n,x):v.attachEvent&&v.attachEvent("on"+M,n):da(n,50))}},w=function(){u!=
h()&&(u=h(),F(x))},H=function(){v.removeEventListener?v.removeEventListener(M,n,x):v.detachEvent&&v.detachEvent("on"+M,n)},q,J="jQueryAddress",M="hashchange",U="change",V="internalChange",W="externalChange",B=!0,x=!1,k={autoUpdate:B,crawlable:x,history:B,strict:B,wrap:x},I=d.browser,D=parseFloat(d.browser.version),Z=I.mozilla,G=I.msie,aa=I.opera,L=I.webkit||I.safari,Q=x,v;try{v=top.document!==q?top:window}catch(fa){v=window}var A=v.document,P=v.history,r=v.location,da=setInterval,E=setTimeout,T=/\/{2,9}/g,
I=navigator.userAgent,y,K=l(document),X=K?K.indexOf("?"):-1,R=A.title,N=x,Y=x,S=B,ba=B,O=x,u=h();if(G){D=parseFloat(I.substr(I.indexOf("MSIE")+4));A.documentMode&&A.documentMode!=D&&(D=8!=A.documentMode?7:8);var ca=A.onpropertychange;A.onpropertychange=function(){ca&&ca.call(A);A.title!=R&&-1!=A.title.indexOf("#"+h())&&(A.title=R)}}if(Q=Z&&1<=D||G&&6<=D||aa&&9.5<=D||L&&523<=D){aa&&(history.navigationMode="compatible");if("complete"==document.readyState)var ea=setInterval(function(){d.address&&(p(),
clearInterval(ea))},50);else t(),d(p);d(window).bind("popstate",w).bind("unload",H)}else!Q&&""!==f()?r.replace(r.href.substr(0,r.href.indexOf("#"))):z();d.address={bind:function(a,c,j){return b(a,c,j)},init:function(a){return b("init",a)},change:function(a){return b(U,a)},internalChange:function(a){return b(V,a)},externalChange:function(a){return b(W,a)},baseURL:function(){var a=r.href;-1!=a.indexOf("#")&&(a=a.substr(0,a.indexOf("#")));/\/$/.test(a)&&(a=a.substr(0,a.length-1));return a},autoUpdate:function(a){return a!==
q?(k.autoUpdate=a,this):k.autoUpdate},crawlable:function(a){return a!==q?(k.crawlable=a,this):k.crawlable},history:function(a){return a!==q?(k.history=a,this):k.history},state:function(a){if(a!==q){k.state=a;var b=c();k.state!==q&&(P.pushState?"/#/"==b.substr(0,3)&&r.replace(k.state.replace(/^\/$/,"")+b.substr(2)):"/"!=b&&b.replace(/^\/#/,"")!=f()&&E(function(){r.replace(k.state.replace(/^\/$/,"")+"/#"+b)},1));return this}return k.state},strict:function(a){return a!==q?(k.strict=a,this):k.strict},
tracker:function(a){return a!==q?(k.tracker=a,this):k.tracker},wrap:function(a){return a!==q?(k.wrap=a,this):k.wrap},update:function(){O=B;this.value(u);O=x;return this},title:function(a){return a!==q?(E(function(){R=A.title=a;ba&&(y&&y.contentWindow&&y.contentWindow.document)&&(y.contentWindow.document.title=a,ba=x);!S&&Z&&r.replace(-1!=r.href.indexOf("#")?r.href:r.href+"#");S=x},50),this):A.title},value:function(a){if(a!==q){a=m(a);"/"==a&&(a="");if(u==a&&!O)return;S=B;u=a;if(k.autoUpdate||O)if(F(B),
e())P[k.history?"pushState":"replaceState"]({},"",k.state.replace(/\/$/,"")+(""===u?"/":u));else N=B,L?k.history?r.hash="#"+g(u,B):r.replace("#"+g(u,B)):u!=h()&&(k.history?r.hash="#"+g(u,B):r.replace("#"+g(u,B))),G&&8>D&&k.history&&E(C,50),L?E(function(){N=x},1):N=x;return this}return!Q?null:m(u)},path:function(a){if(a!==q){var b=this.queryString(),c=this.hash();this.value(a+(b?"?"+b:"")+(c?"#"+c:""));return this}return m(u).split("#")[0].split("?")[0]},pathNames:function(){var a=this.path(),b=a.replace(T,
"/").split("/");("/"==a.substr(0,1)||0===a.length)&&b.splice(0,1);"/"==a.substr(a.length-1,1)&&b.splice(b.length-1,1);return b},queryString:function(a){if(a!==q){var b=this.hash();this.value(this.path()+(a?"?"+a:"")+(b?"#"+b:""));return this}a=u.split("?");return a.slice(1,a.length).join("?").split("#")[0]},parameter:function(a,b,c){var j,e;if(b!==q){var g=this.parameterNames();e=[];b=b?b.toString():"";for(j=0;j<g.length;j++){var l=g[j],f=this.parameter(l);"string"==typeof f&&(f=[f]);l==a&&(f=null===
b||""===b?[]:c?f.concat([b]):[b]);for(var n=0;n<f.length;n++)e.push(l+"="+f[n])}-1==d.inArray(a,g)&&null!==b&&""!==b&&e.push(a+"="+b);this.queryString(e.join("&"));return this}if(b=this.queryString()){c=[];e=b.split("&");for(j=0;j<e.length;j++)b=e[j].split("="),b[0]==a&&c.push(b.slice(1).join("="));if(0!==c.length)return 1!=c.length?c:c[0]}},parameterNames:function(){var a=this.queryString(),b=[];if(a&&-1!=a.indexOf("="))for(var a=a.split("&"),c=0;c<a.length;c++){var j=a[c].split("=")[0];-1==d.inArray(j,
b)&&b.push(j)}return b},hash:function(a){if(a!==q)return this.value(u.split("#")[0]+(a?"#"+a:"")),this;a=u.split("#");return a.slice(1,a.length).join("#")}};d.fn.address=function(a){if(!d(this).attr("address")){var b=function(b){if(b.shiftKey||b.ctrlKey||b.metaKey)return!0;if(d(this).is("a")){var c=a?a.call(this):/address:/.test(d(this).attr("rel"))?d(this).attr("rel").split("address:")[1].split(" ")[0]:void 0!==d.address.state()&&"/"!=d.address.state()?d(this).attr("href").replace(RegExp("^(.*"+
d.address.state()+"|\\.)"),""):d(this).attr("href").replace(/^(#\!?|\.)/,"");d.address.value(c);b.preventDefault()}};d(this).click(b).live("click",b).live("submit",function(b){if(d(this).is("form")){var c=d(this).attr("action"),c=a?a.call(this):(-1!=c.indexOf("?")?c.replace(/&$/,""):c+"?")+d(this).serialize();d.address.value(c);b.preventDefault()}}).attr("address",!0)}return this}})(jQuery);jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"easeOutQuad",swing:function(d,a,b,e,c){return jQuery.easing[jQuery.easing.def](d,a,b,e,c)},easeInQuad:function(d,a,b,e,c){return e*(a/=c)*a+b},easeOutQuad:function(d,a,b,e,c){return-e*(a/=c)*(a-2)+b},easeInOutQuad:function(d,a,b,e,c){return 1>(a/=c/2)?e/2*a*a+b:-e/2*(--a*(a-2)-1)+b},easeInCubic:function(d,a,b,e,c){return e*(a/=c)*a*a+b},easeOutCubic:function(d,a,b,e,c){return e*((a=a/c-1)*a*a+1)+b},easeInOutCubic:function(d,a,b,e,c){return 1>(a/=c/2)?e/2*a*a*a+b:
e/2*((a-=2)*a*a+2)+b},easeInQuart:function(d,a,b,e,c){return e*(a/=c)*a*a*a+b},easeOutQuart:function(d,a,b,e,c){return-e*((a=a/c-1)*a*a*a-1)+b},easeInOutQuart:function(d,a,b,e,c){return 1>(a/=c/2)?e/2*a*a*a*a+b:-e/2*((a-=2)*a*a*a-2)+b},easeInQuint:function(d,a,b,e,c){return e*(a/=c)*a*a*a*a+b},easeOutQuint:function(d,a,b,e,c){return e*((a=a/c-1)*a*a*a*a+1)+b},easeInOutQuint:function(d,a,b,e,c){return 1>(a/=c/2)?e/2*a*a*a*a*a+b:e/2*((a-=2)*a*a*a*a+2)+b},easeInSine:function(d,a,b,e,c){return-e*Math.cos(a/
c*(Math.PI/2))+e+b},easeOutSine:function(d,a,b,e,c){return e*Math.sin(a/c*(Math.PI/2))+b},easeInOutSine:function(d,a,b,e,c){return-e/2*(Math.cos(Math.PI*a/c)-1)+b},easeInExpo:function(d,a,b,e,c){return 0==a?b:e*Math.pow(2,10*(a/c-1))+b},easeOutExpo:function(d,a,b,e,c){return a==c?b+e:e*(-Math.pow(2,-10*a/c)+1)+b},easeInOutExpo:function(d,a,b,e,c){return 0==a?b:a==c?b+e:1>(a/=c/2)?e/2*Math.pow(2,10*(a-1))+b:e/2*(-Math.pow(2,-10*--a)+2)+b},easeInCirc:function(d,a,b,e,c){return-e*(Math.sqrt(1-(a/=c)*
a)-1)+b},easeOutCirc:function(d,a,b,e,c){return e*Math.sqrt(1-(a=a/c-1)*a)+b},easeInOutCirc:function(d,a,b,e,c){return 1>(a/=c/2)?-e/2*(Math.sqrt(1-a*a)-1)+b:e/2*(Math.sqrt(1-(a-=2)*a)+1)+b},easeInElastic:function(d,a,b,e,c){d=1.70158;var f=0,h=e;if(0==a)return b;if(1==(a/=c))return b+e;f||(f=0.3*c);h<Math.abs(e)?(h=e,d=f/4):d=f/(2*Math.PI)*Math.asin(e/h);return-(h*Math.pow(2,10*(a-=1))*Math.sin((a*c-d)*2*Math.PI/f))+b},easeOutElastic:function(d,a,b,e,c){d=1.70158;var f=0,h=e;if(0==a)return b;if(1==
(a/=c))return b+e;f||(f=0.3*c);h<Math.abs(e)?(h=e,d=f/4):d=f/(2*Math.PI)*Math.asin(e/h);return h*Math.pow(2,-10*a)*Math.sin((a*c-d)*2*Math.PI/f)+e+b},easeInOutElastic:function(d,a,b,e,c){d=1.70158;var f=0,h=e;if(0==a)return b;if(2==(a/=c/2))return b+e;f||(f=c*0.3*1.5);h<Math.abs(e)?(h=e,d=f/4):d=f/(2*Math.PI)*Math.asin(e/h);return 1>a?-0.5*h*Math.pow(2,10*(a-=1))*Math.sin((a*c-d)*2*Math.PI/f)+b:0.5*h*Math.pow(2,-10*(a-=1))*Math.sin((a*c-d)*2*Math.PI/f)+e+b},easeInBack:function(d,a,b,e,c,f){void 0==
f&&(f=1.70158);return e*(a/=c)*a*((f+1)*a-f)+b},easeOutBack:function(d,a,b,e,c,f){void 0==f&&(f=1.70158);return e*((a=a/c-1)*a*((f+1)*a+f)+1)+b},easeInOutBack:function(d,a,b,e,c,f){void 0==f&&(f=1.70158);return 1>(a/=c/2)?e/2*a*a*(((f*=1.525)+1)*a-f)+b:e/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+b},easeInBounce:function(d,a,b,e,c){return e-jQuery.easing.easeOutBounce(d,c-a,0,e,c)+b},easeOutBounce:function(d,a,b,e,c){return(a/=c)<1/2.75?e*7.5625*a*a+b:a<2/2.75?e*(7.5625*(a-=1.5/2.75)*a+0.75)+b:a<2.5/2.75?
e*(7.5625*(a-=2.25/2.75)*a+0.9375)+b:e*(7.5625*(a-=2.625/2.75)*a+0.984375)+b},easeInOutBounce:function(d,a,b,e,c){return a<c/2?0.5*jQuery.easing.easeInBounce(d,2*a,0,e,c)+b:0.5*jQuery.easing.easeOutBounce(d,2*a-c,0,e,c)+0.5*e+b}});
(function(d,a,b){var e,c,f,h;f={paneClass:"pane",sliderClass:"slider",contentClass:"content",iOSNativeScrolling:!1,preventPageScrolling:!1,disableResize:!1,alwaysVisible:!1,flashDelay:1500,sliderMinHeight:20,sliderMaxHeight:null};e="Microsoft Internet Explorer"===a.navigator.appName&&/msie 7./i.test(a.navigator.appVersion)&&a.ActiveXObject;c=null;h=function(){var a,c,d;return a=b.createElement("div"),c=a.style,c.position="absolute",c.width="100px",c.height="100px",c.overflow="scroll",c.top="-9999px",
b.body.appendChild(a),d=a.offsetWidth-a.clientWidth,b.body.removeChild(a),d};var m,g=function(j,e){this.el=j;this.options=e;c||(c=h());this.$el=d(this.el);this.doc=d(b);this.win=d(a);this.$content=this.$el.children("."+e.contentClass);this.$content.attr("tabindex",0);this.content=this.$content[0];this.options.iOSNativeScrolling&&null!=this.el.style.WebkitOverflowScrolling?this.nativeScrolling():this.generate();this.createEvents();this.addEvents();this.reset()};m=(g.prototype.preventScrolling=function(a,
b){this.isActive&&("DOMMouseScroll"===a.type?("down"===b&&0<a.originalEvent.detail||"up"===b&&0>a.originalEvent.detail)&&a.preventDefault():"mousewheel"===a.type&&a.originalEvent&&a.originalEvent.wheelDelta&&("down"===b&&0>a.originalEvent.wheelDelta||"up"===b&&0<a.originalEvent.wheelDelta)&&a.preventDefault())},g.prototype.nativeScrolling=function(){this.$content.css({WebkitOverflowScrolling:"touch"});this.isActive=this.iOSNativeScrolling=!0},g.prototype.updateScrollValues=function(){var a;a=this.content;
this.maxScrollTop=a.scrollHeight-a.clientHeight;this.contentScrollTop=a.scrollTop;this.iOSNativeScrolling||(this.maxSliderTop=this.paneHeight-this.sliderHeight,this.sliderTop=this.contentScrollTop*this.maxSliderTop/this.maxScrollTop)},g.prototype.createEvents=function(){var a=this;this.events={down:function(b){return a.isBeingDragged=!0,a.offsetY=b.pageY-a.slider.offset().top,a.pane.addClass("active"),a.doc.bind("mousemove",a.events.drag).bind("mouseup",a.events.up),!1},drag:function(b){return a.sliderY=
b.pageY-a.$el.offset().top-a.offsetY,a.scroll(),a.updateScrollValues(),a.contentScrollTop>=a.maxScrollTop?a.$el.trigger("scrollend"):0===a.contentScrollTop&&a.$el.trigger("scrolltop"),!1},up:function(){return a.isBeingDragged=!1,a.pane.removeClass("active"),a.doc.unbind("mousemove",a.events.drag).unbind("mouseup",a.events.up),!1},resize:function(){a.reset()},panedown:function(b){return a.sliderY=(b.offsetY||b.originalEvent.layerY)-0.5*a.sliderHeight,a.scroll(),a.events.down(b),!1},scroll:function(b){a.isBeingDragged||
(a.updateScrollValues(),a.iOSNativeScrolling||(a.sliderY=a.sliderTop,a.slider.css({top:a.sliderTop})),null!=b&&(a.contentScrollTop>=a.maxScrollTop?(a.options.preventPageScrolling&&a.preventScrolling(b,"down"),a.$el.trigger("scrollend")):0===a.contentScrollTop&&(a.options.preventPageScrolling&&a.preventScrolling(b,"up"),a.$el.trigger("scrolltop"))))},wheel:function(b){if(null!=b)return a.sliderY+=-b.wheelDeltaY||-b.delta,a.scroll(),!1}}},g.prototype.addEvents=function(){var a;this.removeEvents();a=
this.events;this.options.disableResize||this.win.bind("resize",a.resize);this.iOSNativeScrolling||(this.slider.bind("mousedown",a.down),this.pane.bind("mousedown",a.panedown).bind("mousewheel DOMMouseScroll",a.wheel));this.$content.bind("scroll mousewheel DOMMouseScroll touchmove",a.scroll)},g.prototype.removeEvents=function(){var a;a=this.events;this.win.unbind("resize",a.resize);this.iOSNativeScrolling||(this.slider.unbind(),this.pane.unbind());this.$content.unbind("scroll mousewheel DOMMouseScroll touchmove",
a.scroll)},g.prototype.generate=function(){var a,b,d,e;return b=this.options,d=b.paneClass,e=b.sliderClass,!this.$el.find(""+d).length&&!this.$el.find(""+e).length&&this.$el.append('<div class="'+d+'"><div class="'+e+'" /></div>'),this.slider=this.$el.find("."+e),this.pane=this.$el.find("."+d),c&&(a="rtl"===this.$el.css("direction")?{left:-c}:{right:-c},this.$el.addClass("has-scrollbar")),null!=a&&this.$content.css(a),this},g.prototype.restore=function(){this.stopped=!1;this.pane.show();this.addEvents()},
g.prototype.reset=function(){var a,b,d,g,f,h,m,p,w;if(this.iOSNativeScrolling)this.contentHeight=this.content.scrollHeight;else return this.$el.find("."+this.options.paneClass).length||this.generate().stop(),this.stopped&&this.restore(),a=this.content,d=a.style,g=d.overflowY,e&&this.$content.css({height:this.$content.height()}),b=a.scrollHeight+c,h=this.pane.outerHeight(),p=parseInt(this.pane.css("top"),10),f=parseInt(this.pane.css("bottom"),10),m=h+p+f,w=Math.round(m/b*m),w<this.options.sliderMinHeight?
w=this.options.sliderMinHeight:null!=this.options.sliderMaxHeight&&w>this.options.sliderMaxHeight&&(w=this.options.sliderMaxHeight),"scroll"===g&&"scroll"!==d.overflowX&&(w+=c),this.maxSliderTop=m-w,this.contentHeight=b,this.paneHeight=h,this.paneOuterHeight=m,this.sliderHeight=w,this.slider.height(w),this.events.scroll(),this.pane.show(),this.isActive=!0,a.scrollHeight===a.clientHeight||this.pane.outerHeight(!0)>=a.scrollHeight&&"scroll"!==g?(this.pane.hide(),this.isActive=!1):this.el.clientHeight===
a.scrollHeight&&"scroll"===g?this.slider.hide():this.slider.show(),this.pane.css({opacity:this.options.alwaysVisible?1:"",visibility:this.options.alwaysVisible?"visible":""}),this},g.prototype.scroll=function(){if(this.isActive)return this.sliderY=Math.max(0,this.sliderY),this.sliderY=Math.min(this.maxSliderTop,this.sliderY),this.$content.scrollTop(-1*((this.paneHeight-this.contentHeight+c)*this.sliderY/this.maxSliderTop)),this.iOSNativeScrolling||this.slider.css({top:this.sliderY}),this},g.prototype.scrollBottom=
function(a){if(this.isActive)return this.reset(),this.$content.scrollTop(this.contentHeight-this.$content.height()-a).trigger("mousewheel"),this},g.prototype.scrollTop=function(a){if(this.isActive)return this.reset(),this.$content.scrollTop(+a).trigger("mousewheel"),this},g.prototype.scrollTo=function(a){if(this.isActive)return this.reset(),this.scrollTop(d(a).get(0).offsetTop),this},g.prototype.stop=function(){return this.stopped=!0,this.removeEvents(),this.pane.hide(),this},g.prototype.flash=function(){var a=
this;if(this.isActive)return this.reset(),this.pane.addClass("flashed"),setTimeout(function(){a.pane.removeClass("flashed")},this.options.flashDelay),this},g);d.fn.nanoScroller=function(a){return this.each(function(){var b,c;(c=this.nanoscroller)||(b=d.extend({},f,a),this.nanoscroller=c=new m(this,b));if(a&&"object"==typeof a){d.extend(c.options,a);if(a.scrollBottom)return c.scrollBottom(a.scrollBottom);if(a.scrollTop)return c.scrollTop(a.scrollTop);if(a.scrollTo)return c.scrollTo(a.scrollTo);if("bottom"===
a.scroll)return c.scrollBottom(0);if("top"===a.scroll)return c.scrollTop(0);if(a.scroll&&a.scroll instanceof d)return c.scrollTo(a.scroll);if(a.stop)return c.stop();if(a.flash)return c.flash()}return c.reset()})}})(jQuery,window,document);
(function(d){function a(a){var e=a.pageX;a=a.pageY;for(var h=-1,m=d([]);m[0]=b[++h];)m.triggerHandler("proximity",[e,a])}var b=d([]),e=d(document);d.event.special.proximity={defaults:{max:100,min:0,throttle:0,fireOutOfBounds:1},setup:function(){b[0]||e.mousemove(a);b=b.add(this)},add:function(a){var b=a.handler,e=d.extend({},d.event.special.proximity.defaults,a.data),m=0,g=0,j=d(this);a.handler=function(a,c,d){var z=e.max,C=e.min,t=e.throttle,p=+new Date,w=e.fireOutOfBounds;if(!(t&&m+t>p)){m=p;var H,
q,p=j.offset(),t=p.left;H=p.top;p=t+j.outerWidth();q=H+j.outerHeight();H=d>q?q:d>H?d:H;t=Math.abs((c>p?p:c>t?c:t)-c);p=Math.abs(H-d);t=Math.sqrt(t*t+p*p);p=t<z&&t>C;if(w||p){if(p)g=0;else{if("number"===typeof w&&g>w)return;++g}z=a.proximity=1-(t<z?t<C?0:t/z:1);a.distance=t;a.pageX=c;a.pageY=d;a.data=e;return b.call(this,a,z,t)}}}},teardown:function(){b=b.not(this);b[0]||e.unbind("mousemove",a)}}})(jQuery);
(function(d){for(var a,b=document.getElementsByTagName("head")[0].style,e=["transformProperty","WebkitTransform","OTransform","msTransform","MozTransform"],c=0;c<e.length;c++)void 0!==b[e[c]]&&(a=e[c]);b="v"=="\v";jQuery.fn.extend({rotate:function(a){if(!(0===this.length||"undefined"==typeof a)){"number"==typeof a&&(a={angle:a});for(var b=[],c=0,e=this.length;c<e;c++){var f=this.get(c);if(!f.Wilq32||!f.Wilq32.PhotoEffect){var h=d.extend(!0,{},a),f=(new Wilq32.PhotoEffect(f,h))._rootObj;b.push(d(f))}else f.Wilq32.PhotoEffect._handleRotation(a)}return b}},
getRotateAngle:function(){for(var a=[],b=0,c=this.length;b<c;b++){var d=this.get(b);d.Wilq32&&d.Wilq32.PhotoEffect&&(a[b]=d.Wilq32.PhotoEffect._angle)}return a},stopRotate:function(){for(var a=0,b=this.length;a<b;a++){var c=this.get(a);c.Wilq32&&c.Wilq32.PhotoEffect&&clearTimeout(c.Wilq32.PhotoEffect._timer)}}});Wilq32=window.Wilq32||{};Wilq32.PhotoEffect=a?function(a,b){a.Wilq32={PhotoEffect:this};this._img=this._rootObj=this._eventObj=a;this._handleRotation(b)}:function(a,b){this._img=a;this._rootObj=
document.createElement("span");this._rootObj.style.display="inline-block";this._rootObj.Wilq32={PhotoEffect:this};a.parentNode.insertBefore(this._rootObj,a);if(a.complete)this._Loader(b);else{var c=this;jQuery(this._img).bind("load",function(){c._Loader(b)})}};var f=Math.PI/180;Wilq32.PhotoEffect.prototype={_setupParameters:function(a){this._parameters=this._parameters||{};"number"!==typeof this._angle&&(this._angle=0);"number"===typeof a.angle&&(this._angle=a.angle);this._parameters.animateTo="number"===
typeof a.animateTo?a.animateTo:this._angle;this._parameters.step=a.step||this._parameters.step||null;this._parameters.easing=a.easing||this._parameters.easing||function(a,b,c,d,e){return-d*((b=b/e-1)*b*b*b-1)+c};this._parameters.duration=a.duration||this._parameters.duration||1E3;this._parameters.callback=a.callback||this._parameters.callback||function(){};a.bind&&a.bind!=this._parameters.bind&&this._BindEvents(a.bind)},_handleRotation:function(a){this._setupParameters(a);this._angle==this._parameters.animateTo?
this._rotate(this._angle):this._animateStart()},_BindEvents:function(a){if(a&&this._eventObj){if(this._parameters.bind){var b=this._parameters.bind,c;for(c in b)b.hasOwnProperty(c)&&jQuery(this._eventObj).unbind(c,b[c])}this._parameters.bind=a;for(c in a)a.hasOwnProperty(c)&&jQuery(this._eventObj).bind(c,a[c])}},_Loader:b?function(a){var b=this._img.width,c=this._img.height;this._img.parentNode.removeChild(this._img);this._vimage=this.createVMLNode("image");this._vimage.src=this._img.src;this._vimage.style.height=
c+"px";this._vimage.style.width=b+"px";this._vimage.style.position="absolute";this._vimage.style.top="0px";this._vimage.style.left="0px";this._container=this.createVMLNode("group");this._container.style.width=b;this._container.style.height=c;this._container.style.position="absolute";this._container.setAttribute("coordsize",b-1+","+(c-1));this._container.appendChild(this._vimage);this._rootObj.appendChild(this._container);this._rootObj.style.position="relative";this._rootObj.style.width=b+"px";this._rootObj.style.height=
c+"px";this._rootObj.setAttribute("id",this._img.getAttribute("id"));this._rootObj.className=this._img.className;this._eventObj=this._rootObj;this._handleRotation(a)}:function(a){this._rootObj.setAttribute("id",this._img.getAttribute("id"));this._rootObj.className=this._img.className;this._width=this._img.width;this._height=this._img.height;this._widthHalf=this._width/2;this._heightHalf=this._height/2;var b=Math.sqrt(this._height*this._height+this._width*this._width);this._widthAdd=b-this._width;
this._heightAdd=b-this._height;this._widthAddHalf=this._widthAdd/2;this._heightAddHalf=this._heightAdd/2;this._img.parentNode.removeChild(this._img);this._aspectW=(parseInt(this._img.style.width,10)||this._width)/this._img.width;this._aspectH=(parseInt(this._img.style.height,10)||this._height)/this._img.height;this._canvas=document.createElement("canvas");this._canvas.setAttribute("width",this._width);this._canvas.style.position="relative";this._canvas.style.left=-this._widthAddHalf+"px";this._canvas.style.top=
-this._heightAddHalf+"px";this._canvas.Wilq32=this._rootObj.Wilq32;this._rootObj.appendChild(this._canvas);this._rootObj.style.width=this._width+"px";this._rootObj.style.height=this._height+"px";this._eventObj=this._canvas;this._cnv=this._canvas.getContext("2d");this._handleRotation(a)},_animateStart:function(){this._timer&&clearTimeout(this._timer);this._animateStartTime=+new Date;this._animateStartAngle=this._angle;this._animate()},_animate:function(){var a=+new Date,b=a-this._animateStartTime>
this._parameters.duration;if(b&&!this._parameters.animatedGif)clearTimeout(this._timer);else{(this._canvas||this._vimage||this._img)&&this._rotate(~~(10*this._parameters.easing(0,a-this._animateStartTime,this._animateStartAngle,this._parameters.animateTo-this._animateStartAngle,this._parameters.duration))/10);this._parameters.step&&this._parameters.step(this._angle);var c=this;this._timer=setTimeout(function(){c._animate.call(c)},10)}this._parameters.callback&&b&&(this._angle=this._parameters.animateTo,
this._rotate(this._angle),this._parameters.callback.call(this._rootObj))},_rotate:b?function(a){this._angle=a;this._container.style.rotation=a%360+"deg"}:a?function(b){this._angle=b;this._img.style[a]="rotate("+b%360+"deg)"}:function(a){this._angle=a;a=a%360*f;this._canvas.width=this._width+this._widthAdd;this._canvas.height=this._height+this._heightAdd;this._cnv.translate(this._widthAddHalf,this._heightAddHalf);this._cnv.translate(this._widthHalf,this._heightHalf);this._cnv.rotate(a);this._cnv.translate(-this._widthHalf,
-this._heightHalf);this._cnv.scale(this._aspectW,this._aspectH);this._cnv.drawImage(this._img,0,0)}};if(b){var b=Wilq32.PhotoEffect.prototype,h;document.createStyleSheet().addRule(".rvml","behavior:url(#default#VML)");try{h=(!document.namespaces.rvml&&document.namespaces.add("rvml","urn:schemas-microsoft-com:vml"),function(a){return document.createElement("<rvml:"+a+' class="rvml">')})}catch(m){h=function(a){return document.createElement("<"+a+' xmlns="urn:schemas-microsoft.com:vml" class="rvml">')}}b.createVMLNode=
h}})(jQuery);
(function(d){d&&(d.events={DOMNodeInserted:function(a){a=a.target;var b=a.nodeName;1==a.nodeType&&(/link/i.test(b)?d.link(a):/style/i.test(b)?d.styleElement(a):a.hasAttribute("style")&&d.styleAttribute(a))},DOMAttrModified:function(a){"style"===a.attrName&&(document.removeEventListener("DOMAttrModified",d.events.DOMAttrModified,!1),d.styleAttribute(a.target),document.addEventListener("DOMAttrModified",d.events.DOMAttrModified,!1))}},document.addEventListener("DOMContentLoaded",function(){document.addEventListener("DOMNodeInserted",d.events.DOMNodeInserted,
!1);document.addEventListener("DOMAttrModified",d.events.DOMAttrModified,!1)},!1))})(window.StyleFix);
(function(d){if(d&&window.CSSStyleDeclaration)for(var a=0;a<d.properties.length;a++){var b=StyleFix.camelCase(d.properties[a]),e=d.prefixProperty(b),c=CSSStyleDeclaration.prototype,f=function(a){return function(){return this[a]}}(e),e=function(a){return function(b){this[a]=b}}(e);Object.defineProperty?Object.defineProperty(c,b,{get:f,set:e,enumerable:!0,configurable:!0}):c.__defineGetter__&&(c.__defineGetter__(b,f),c.__defineSetter__(b,e))}})(window.PrefixFree);
(function(d,a){if(d&&a)for(var b=0;b<a.properties.length;b++){var e=a.properties[b],c=StyleFix.camelCase(e),e=a.prefixProperty(e,!0);d.cssProps[c]=e}})(window.jQuery,window.PrefixFree);
(function(){function d(a,d){return[].slice.call((d||document).querySelectorAll(a))}if(window.addEventListener){var a=window.StyleFix={link:function(b){try{if("stylesheet"!==b.rel||b.hasAttribute("data-noprefix"))return}catch(d){return}var c=b.href||b.getAttribute("data-href"),f=c.replace(/[^\/]+$/,""),h=(/^[a-z]{3,10}:/.exec(f)||[""])[0],m=(/^[a-z]{3,10}:\/\/[^\/]+/.exec(f)||[""])[0],g=/^([^?]*)\??/.exec(c)[1],j=b.parentNode,l=new XMLHttpRequest,n;l.onreadystatechange=function(){4===l.readyState&&
n()};n=function(){var c=l.responseText;if(c&&b.parentNode&&(!l.status||400>l.status||600<l.status)){c=a.fix(c,!0,b);if(f)var c=c.replace(/url\(\s*?((?:"|')?)(.+?)\1\s*?\)/gi,function(a,b,c){return/^([a-z]{3,10}:|#)/i.test(c)?a:/^\/\//.test(c)?'url("'+h+c+'")':/^\//.test(c)?'url("'+m+c+'")':/^\?/.test(c)?'url("'+g+c+'")':'url("'+f+c+'")'}),d=f.replace(/([\\\^\$*+[\]?{}.=!:(|)])/g,"\\$1"),c=c.replace(RegExp("\\b(behavior:\\s*?url\\('?\"?)"+d,"gi"),"$1");d=document.createElement("style");d.textContent=
c;d.media=b.media;d.disabled=b.disabled;d.setAttribute("data-href",b.getAttribute("href"));j.insertBefore(d,b);j.removeChild(b);d.media=b.media}};try{l.open("GET",c),l.send(null)}catch(F){"undefined"!=typeof XDomainRequest&&(l=new XDomainRequest,l.onerror=l.onprogress=function(){},l.onload=n,l.open("GET",c),l.send(null))}b.setAttribute("data-inprogress","")},styleElement:function(b){if(!b.hasAttribute("data-noprefix")){var d=b.disabled;b.textContent=a.fix(b.textContent,!0,b);b.disabled=d}},styleAttribute:function(b){var d=
b.getAttribute("style"),d=a.fix(d,!1,b);b.setAttribute("style",d)},process:function(){d('link[rel="stylesheet"]:not([data-inprogress])').forEach(StyleFix.link);d("style").forEach(StyleFix.styleElement);d("[style]").forEach(StyleFix.styleAttribute)},register:function(b,d){(a.fixers=a.fixers||[]).splice(void 0===d?a.fixers.length:d,0,b)},fix:function(b,d,c){for(var f=0;f<a.fixers.length;f++)b=a.fixers[f](b,d,c)||b;return b},camelCase:function(a){return a.replace(/-([a-z])/g,function(a,b){return b.toUpperCase()}).replace("-",
"")},deCamelCase:function(a){return a.replace(/[A-Z]/g,function(a){return"-"+a.toLowerCase()})}};setTimeout(function(){d('link[rel="stylesheet"]').forEach(StyleFix.link)},10);document.addEventListener("DOMContentLoaded",StyleFix.process,!1)}})();
(function(d){function a(a,c,d,e,f){a=b[a];a.length&&(a=RegExp(c+"("+a.join("|")+")"+d,"gi"),f=f.replace(a,e));return f}if(window.StyleFix&&window.getComputedStyle){var b=window.PrefixFree={prefixCSS:function(c,d){var e=b.prefix;-1<b.functions.indexOf("linear-gradient")&&(c=c.replace(/(\s|:|,)(repeating-)?linear-gradient\(\s*(-?\d*\.?\d*)deg/ig,function(a,b,c,d){return b+(c||"")+"linear-gradient("+(90-d)+"deg"}));c=a("functions","(\\s|:|,)","\\s*\\(","$1"+e+"$2(",c);c=a("keywords","(\\s|:)","(\\s|;|\\}|$)",
"$1"+e+"$2$3",c);c=a("properties","(^|\\{|\\s|;)","\\s*:","$1"+e+"$2:",c);if(b.properties.length){var f=RegExp("\\b("+b.properties.join("|")+")(?!:)","gi");c=a("valueProperties","\\b",":(.+?);",function(a){return a.replace(f,e+"$1")},c)}d&&(c=a("selectors","","\\b",b.prefixSelector,c),c=a("atrules","@","\\b","@"+e+"$1",c));c=c.replace(RegExp("-"+e,"g"),"-");return c=c.replace(/-\*-(?=[a-z]+)/gi,b.prefix)},property:function(a){return(b.properties.indexOf(a)?b.prefix:"")+a},value:function(c){c=a("functions",
"(^|\\s|,)","\\s*\\(","$1"+b.prefix+"$2(",c);return a("keywords","(^|\\s)","(\\s|$)","$1"+b.prefix+"$2$3",c)},prefixSelector:function(a){return a.replace(/^:{1,2}/,function(a){return a+b.prefix})},prefixProperty:function(a,c){var d=b.prefix+a;return c?StyleFix.camelCase(d):d}},e={},c=[],f=getComputedStyle(document.documentElement,null),h=document.createElement("div").style,m=function(a){if("-"===a.charAt(0)){c.push(a);a=a.split("-");var b=a[1];for(e[b]=++e[b]||1;3<a.length;)a.pop(),b=a.join("-"),
StyleFix.camelCase(b)in h&&-1===c.indexOf(b)&&c.push(b)}};if(0<f.length)for(var g=0;g<f.length;g++)m(f[g]);else for(var j in f)m(StyleFix.deCamelCase(j));var g=0,l,n;for(n in e)f=e[n],g<f&&(l=n,g=f);b.prefix="-"+l+"-";b.Prefix=StyleFix.camelCase(b.prefix);b.properties=[];for(g=0;g<c.length;g++)j=c[g],0===j.indexOf(b.prefix)&&(l=j.slice(b.prefix.length),StyleFix.camelCase(l)in h||b.properties.push(l));"Ms"==b.Prefix&&!("transform"in h)&&(!("MsTransform"in h)&&"msTransform"in h)&&b.properties.push("transform",
"transform-origin");b.properties.sort();l=function(a,b){F[b]="";F[b]=a;return!!F[b]};n={"linear-gradient":{property:"backgroundImage",params:"red, teal"},calc:{property:"width",params:"1px + 5%"},element:{property:"backgroundImage",params:"#foo"},"cross-fade":{property:"backgroundImage",params:"url(a.png), url(b.png), 50%"}};n["repeating-linear-gradient"]=n["repeating-radial-gradient"]=n["radial-gradient"]=n["linear-gradient"];g={initial:"color","zoom-in":"cursor","zoom-out":"cursor",box:"display",
flexbox:"display","inline-flexbox":"display",flex:"display","inline-flex":"display"};b.functions=[];b.keywords=[];var F=document.createElement("div").style,z;for(z in n)m=n[z],f=m.property,m=z+"("+m.params+")",!l(m,f)&&l(b.prefix+m,f)&&b.functions.push(z);for(var C in g)f=g[C],!l(C,f)&&l(b.prefix+C,f)&&b.keywords.push(C);z=function(a){t.textContent=a+"{}";return!!t.sheet.cssRules.length};C={":read-only":null,":read-write":null,":any-link":null,"::selection":null};l={keyframes:"name",viewport:null,
document:'regexp(".")'};b.selectors=[];b.atrules=[];var t=d.appendChild(document.createElement("style")),p;for(p in C)n=p+(C[p]?"("+C[p]+")":""),!z(n)&&z(b.prefixSelector(n))&&b.selectors.push(p);for(var w in l)n=w+" "+(l[w]||""),!z("@"+n)&&z("@"+b.prefix+n)&&b.atrules.push(w);d.removeChild(t);b.valueProperties=["transition","transition-property"];d.className+=" "+b.prefix;StyleFix.register(b.prefixCSS)}})(document.documentElement);var title="",aniSpd=5E3,fadeSpd=200,menu;
function setCssR(d){vright=$(d).css("right");vtop=$(d).css("top");$(d).css({right:vright,top:vtop})}function inputBlur(){}function setCssL(d){vleft=$(d).css("left");vtop=$(d).css("top");$(d).css({left:vleft,top:vtop})}function setMenu(d){menu=d}function loadingAnimation(d){d?($("#light").show(),$(".spinner").show()):($("#light").fadeOut(),$(".spinner").fadeOut())}
function loadArt(){$("#hidden-art").append($("<img id='general'/>").attr("src","/"+subDir+"/img/general.jpg"));$("#hidden-art").append($("<img id='fine_arts'/>").attr("src","/"+subDir+"/img/fine_arts.jpg"));$("#hidden-art").append($("<img id='music'/>").attr("src","/"+subDir+"/img/music.jpg"));$("#hidden-art").append($("<img id='dance'/>").attr("src","/"+subDir+"/img/dance.jpg"));$("#hidden-art").append($("<img id='thematic'/>").attr("src","/"+subDir+"/img/thematic.jpg"));$("#hidden-art").append($("<img id='literary'/>").attr("src",
"/"+subDir+"/img/literary.jpg"));$("#hidden-art").append($("<img id='dramatics'/>").attr("src","/"+subDir+"/img/dramatics.jpg"))}function lookup(d){0==d.length?$("#suggestions").fadeOut():($("#suggestions").fadeIn(),$("#s-loader").show(),$.post("search.php",{q:""+d+""},function(a){$("#suggestions").html(a);$("#s-loader").hide()}))}
(function(d){var a=d.History;if(!a.enabled)return!1;$(function(){$("#suggestions").fadeOut();$(d).width();$(d).height();$("body").keydown(function(a){27==a.which&&$("#shortcut").hide();37<=a.which&&40>=a.which&&$.getScript("/"+subDir+"/js/shortcut.js",function(){$("#shortcut").show()})});a.Adapter.bind(d,"statechange",function(){var b=a.getState(),d=a.getRootUrl(),b=b.url.replace(d+subDir+"/","");if(""==b)"moveout"==$("#mainmenu-pane").attr("class")?($("#mainmenu-pane").attr("class","movein"),$("#font-pane").attr("class",
"movein")):"pane"==$("#mainmenu-pane").attr("class")&&($("#mainmenu-pane").attr("class","loading"),$("#font-pane").attr("class","loading"),a.pushState({timestamp:(new Date).getTime()},"Ragam 2013","#"));else if("/"==b[b.length-1]&&(b=b.substr(0,b.length-1)),setCssL("#font-pane"),setCssR("#mainmenu-pane"),"Events"==b.split("/")[0])if($(".pane").hide(),$("#inner-pane-events").show(),$("#content-wrapper-events").fadeOut(),"moveout"!=$("#mainmenu-pane").attr("class")&&$("#inner-pane-events").attr("class",
"pane"),$("#mainmenu-pane").attr("class","moveout"),$("#font-pane").attr("class","moveout"),-1==b.search("/"))$("#painting-events").fadeIn(),"moveright"==$("#inner-pane-events").attr("class")&&$("#inner-pane-events").attr("class","moveback"),title=b,$.ajax({dataType:"json",url:"/"+subDir+"/manager/fetchlinks.php",data:{cat:title},type:"POST",success:function(a){setMenu(a);var b="";a.forEach(function(a){b=b+"<a href='/"+subDir+"/"+title+"/"+a.name.replace(/\ /g,"_")+"'><li>"+a.name+"</li></a>"});$("#submenu-links-events").html(b);
loadingAnimation(!1)}});else{$("#painting-events").fadeOut();$("#inner-pane-events").attr("class","moveright");var e=b.split("/");eve=b.split("/")[e.length-1];$.ajax({dataType:"json",url:"/"+subDir+"/manager/content.php",data:{event:eve},type:"POST",success:function(a){null!=a.name?($("#content-heading-events").text(a.name),$("#content-content-events").html(a.content)):$("#content-heading-events").text("Choose an event from right");$("#content-wrapper-events").fadeIn();$(".nano").nanoScroller({scrollTop:"0px"})}});
title=b.split("/")[0];category=b.split("/")[1].replace(/_/g," ");2<e.length&&(subcategory=b.split("/")[2].replace(/_/g," "));$.ajax({dataType:"json",url:"/"+subDir+"/manager/fetchlinks.php",data:{cat:title},type:"POST",success:function(a){setMenu(a);var b="";a.forEach(function(a){b=a.name==category?b+"<a href='/"+subDir+"/"+title+"/"+a.name.replace(/\ /g,"_")+"' class='selected'><li>"+a.name+"</li></a>":b+"<a href='/"+subDir+"/"+title+"/"+a.name.replace(/\ /g,"_")+"' class='notselected'><li>"+a.name+
"</li></a>"});sublinks="";if(2<e.length)for(ele in menu)if(menu[ele].name==category){for(s in menu[ele].sublinks)sublinks=menu[ele].sublinks[s].name==subcategory?sublinks+"<li><a href='/"+subDir+"/"+title+"/"+menu[ele].name.replace(/\ /g,"_")+"/"+menu[ele].sublinks[s].name.replace(/\ /g,"_")+"' class='selected'>"+menu[ele].sublinks[s].name+"<br/><span class='shortdesc'>"+menu[ele].sublinks[s].shortdesc+"</span></a></li>":sublinks+"<li><a href='/"+subDir+"/"+title+"/"+menu[ele].name.replace(/\ /g,
"_")+"/"+menu[ele].sublinks[s].name.replace(/\ /g,"_")+"' class='notselected'>"+menu[ele].sublinks[s].name+"<br/><span class='shortdesc'>"+menu[ele].sublinks[s].shortdesc+"</span></a></li>";break}$("#hidden-submenu-links").html(b);$("#hidden-subsubmenu-links").html(sublinks);$("#submenu-links-events").html($("#hidden-submenu-links").html());$("#subsubmenu-links-events").html($("#hidden-subsubmenu-links").html());loadingAnimation(!1)}})}else"Workshops"==b.split("/")[0]?($(".pane").hide(),$("#inner-pane-workshops").show(),
"moveout"!=$("#mainmenu-pane").attr("class")&&$("#inner-pane-workshops").attr("class","pane"),$("#mainmenu-pane").attr("class","moveout"),$("#font-pane").attr("class","moveout"),-1==b.search("/")?($("#painting-workshops").fadeIn(),title=b,$.ajax({dataType:"json",url:"/"+subDir+"/manager/fetchlinks.php",data:{cat:title},type:"POST",success:function(a){setMenu(a);var b="";a.forEach(function(a){b=b+"<a href='/"+subDir+"/"+title+"/"+a.name.replace(/\ /g,"_")+"'><li>"+a.name+"</li></a>"});$("#submenu-links-workshops").html(b);
loadingAnimation(!1)}})):($("#painting-workshops").fadeOut(),$("#inner-pane-workshops").attr("class","moveright"),e=b.split("/"),eve=b.split("/")[e.length-1],$.ajax({dataType:"json",url:"/"+subDir+"/manager/content.php",data:{event:eve},type:"POST",success:function(a){$("#content-heading-workshops").text(a.name);$("#content-content-workshops").html(a.content);$("#content-wrapper-workshops").fadeIn();$(".nano").nanoScroller({scrollTop:"0px"})}}))):"Proshows"==b.split("/")[0]?($(".pane").hide(),$("#inner-pane-proshows").show(),
"moveout"!=$("#mainmenu-pane").attr("class")&&$("#inner-pane-proshows").attr("class","pane"),$("#mainmenu-pane").attr("class","moveout"),$("#font-pane").attr("class","moveout"),$("#painting-proshows").fadeIn(),title=b,loadingAnimation(!1)):"Showcase"==b.split("/")[0]?($(".pane").hide(),$("#inner-pane-showcase").show(),"moveout"!=$("#mainmenu-pane").attr("class")&&$("#inner-pane-showcase").attr("class","pane"),$("#mainmenu-pane").attr("class","moveout"),$("#font-pane").attr("class","moveout"),-1==
b.search("/")?($("#painting-showcase").fadeIn(),title=b,$.ajax({dataType:"json",url:"/"+subDir+"/manager/fetchlinks.php",data:{cat:title},type:"POST",success:function(a){setMenu(a);var b="";a.forEach(function(a){b=b+"<a href='/"+subDir+"/"+title+"/"+a.name.replace(/\ /g,"_")+"'><li>"+a.name+"</li></a>"});$("#submenu-links-showcase").html(b);loadingAnimation(!1)}})):($("#painting-showcase").fadeOut(),$("#inner-pane-showcase").attr("class","moveright"),e=b.split("/"),eve=b.split("/")[e.length-1],$.ajax({dataType:"json",
url:"/"+subDir+"/manager/content.php",data:{event:eve},type:"POST",success:function(a){$("#content-heading-showcase").text(a.name);$("#content-content-showcase").html(a.content);$("#content-wrapper-showcase").fadeIn();$(".nano").nanoScroller({scrollTop:"0px"})}}))):"Sponsors"==b.split("/")[0]&&($(".pane").hide(),$("#inner-pane-sponsors").show(),"moveout"!=$("#mainmenu-pane").attr("class")&&$("#inner-pane-sponsors").attr("class","pane"),$("#mainmenu-pane").attr("class","moveout"),$("#font-pane").attr("class",
"moveout"),$("#painting-sponsors").fadeIn(),title=b,loadingAnimation(!1))});$(d).bind("load",function(){a.pushState({timestamp:(new Date).getTime()},"Ragam 2013 | National Institute of Technology Calicut","");loadingAnimation(!1)});var b=0,e=$("#ticker div").length;$("#ticker div:first").fadeIn(fadeSpd);d.setInterval(function(){$("#ticker div:eq("+b+")").delay(fadeSpd).fadeOut(fadeSpd);b++;$("#ticker div:eq("+b+")").stop(!0,!0).fadeIn(fadeSpd);e==b&&(b=-1)},aniSpd);$(".nano").hover(function(){$(this).nanoScroller()});
$("#mainlinks a").click(function(a){a.preventDefault()});$("#construction").click(function(){$("#construction").fadeOut();$("#wrapper").attr("class","")});$("#mainlinks li").click(function(){title=$(this).data("title");"Workshops"==$(this).data("title")||"Showcase"==$(this).data("title")?($("#construction").show(),$("#wrapper").attr("class","blur")):(loadingAnimation(!0),a.pushState({timestamp:(new Date).getTime()},title+" | Ragam 2013",$(this).parent("a").attr("href")))});$("#submenu-links-events a").live({mouseenter:function(){var a=
"";for(ele in menu)if(menu[ele].name==$(this).text()){for(s in menu[ele].sublinks)a=a+"<li><a href='/"+subDir+"/"+title+"/"+menu[ele].name.replace(/\ /g,"_")+"/"+menu[ele].sublinks[s].name.replace(/\ /g,"_")+"'>"+menu[ele].sublinks[s].name+"<br/><span class='shortdesc'>"+menu[ele].sublinks[s].shortdesc+"</span></a></li>";break}$("#subsubmenu-links-events").html(a);a=$(this).text();a=a.replace(" ","_");$("#painting-events").hide();$("#painting-events").css("background-image",'url("'+$("img#"+a).attr("src")+
'")');"moveright"!=$("#inner-pane-events").attr("class")&&$("#painting-events").stop(!0,!0).fadeIn(250);$("#submenu-links-events a").each(function(){$(this).attr("class","notselected")});$(this).attr("class","selected")},click:function(a){a.preventDefault()}});$("#subsubmenu-links-events a").live({click:function(b){b.preventDefault();$("#painting-events").fadeOut();$("#subsubmenu-links-events a").each(function(){$(this).attr("class","notselected")});$(this).attr("class","selected");title=$(this).html();
title=title.split("<br>")[0];a.pushState(null,title+" | Ragam 2013",$(this).attr("href"))},mouseenter:function(){$("#subsubmenu-links-events a").each(function(){$(this).attr("class","notselected")});$(this).attr("class","selected");$(this).children(".shortdesc").show()},mouseleave:function(){$(this).children(".shortdesc").hide()}});$("#content-container-events").mouseenter(function(){"moveright"==$("#inner-pane-events").attr("class")&&($("#submenu-links-events").html($("#hidden-submenu-links").html()),
$("#subsubmenu-links-events").html($("#hidden-subsubmenu-links").html()))});$(".menu_click").click(function(){$("#wrapper").attr("class","support-up");$("#support-pane").attr("class","support-up");$("#menu_tab").attr("class","up")});$(document).mouseup(function(a){var b=$("#support-pane");0===b.has(a.target).length&&"support-up"==$("#wrapper").attr("class")&&(b.attr("class","support-down"),$("#wrapper").attr("class","support-down"),$(".menu_item").css({"border-bottom":"0px solid #444"}))});$("#submenu-links-workshops a").live({mouseenter:function(){var a=
"";for(ele in menu)if(menu[ele].name==$(this).text()){for(s in menu[ele].sublinks)a=a+"<li><a href='/"+subDir+"/"+title+"/"+menu[ele].name.replace(/\ /g,"_")+"/"+menu[ele].sublinks[s].name.replace(/\ /g,"_")+"'>"+menu[ele].sublinks[s].name+"<br/><span class='shortdesc'>"+menu[ele].sublinks[s].shortdesc+"</span></a></li>";break}$("#subsubmenu-links-workshops").html(a);a=$(this).text();a=a.replace(" ","_");$("#painting-workshops").hide();$("#painting-workshops").css("background-image",'url("'+$("img#"+
a).attr("src")+'")');$("#painting-workshops").stop(!0,!0).fadeIn(250);$("#submenu-links-workshops a").each(function(){$(this).attr("class","notselected")});$(this).attr("class","selected")},click:function(b){b.preventDefault();a.pushState(null,$(this).text()+" | Ragam 2013",$(this).attr("href"))}});$(".menu_nonclick").click(function(){$("#menu_tab").hasClass("up")&&($("#support-pane").attr("class","support-down"),$("#wrapper").attr("class","support-down"),$(".menu_item").css({"border-bottom":"0px solid #444"}),
$("#menu_tab").removeClass("up"))});$("#home-button").click(function(){a.pushState({timestamp:(new Date).getTime()},"Ragam 2013 | National Institute of Technology Calicut","/"+subDir+"/");$("#font-pane").show();$("#mainmenu-pane").show();$("#support-pane").fadeIn();$("#content-wrapper-events").fadeOut()});$("a#signin-link").click(function(){"cancel"==$("#signin-link").attr("class")?($(this).html('<img src="/'+subDir+'/img/signup.png" />'),$("#signin-link").attr("class","enabled"),$("#dark").attr("class",
"overlayoff"),$("#signup-form-wrapper").hide()):($(this).html('<img src="/'+subDir+'/img/cancel.png" />'),$("a#signin-link").attr("class","cancel"),$("a#login-link").attr("class","enabled"),$("a#login-link").html('<img src="/'+subDir+'/img/login.png" />'),$("#dark").attr("class","overlayon"),$("#login-form-wrapper").hide(),$("#signup-form-wrapper").fadeIn())});$("#login-link").click(function(){"cancel"==$("#login-link").attr("class")?($(this).html('<img src="/'+subDir+'/img/login.png" />'),$("#login-link").attr("class",
"enabled"),$("#dark").attr("class","overlayoff"),$("#login-form-wrapper").hide()):($(this).html('<img src="/'+subDir+'/img/cancel.png" />'),$("a#login-link").attr("class","cancel"),$("a#signin-link").attr("class","enabled"),$("a#signin-link").html('<img src="/'+subDir+'/img/signup.png" />'),$("#dark").attr("class","overlayon"),$("#signup-form-wrapper").hide(),$("#login-form-wrapper").fadeIn())});$("#dark").click(function(){$("#login-link").html('<img src="/'+subDir+'/img/login.png" />');$("#signin-link").html('<img src="/'+
subDir+'/img/signup.png" />');$("#login-link").attr("class","enabled");$("#dark").attr("class","overlayoff");$("#login-form-wrapper").hide();$("#signup-form-wrapper").hide()});$(".gallery").click(function(){$.getScript("/"+subDir+"/js/gallery.js",function(){$("#gallery").show();$("#gallery").attr("class","overlayon")})});$(".feedback_link").click(function(){$("#feedback").show();$("#feedback").attr("class","overlayon")});$("#gallery").click(function(){$("#gallery").hide();$("#gallery").attr("class",
"overlayoff")});$(".menu_item").click(function(){$(this).siblings().css({"border-bottom":"0px solid #444"});$(this).siblings().removeClass("menu_select");$(this).css({"border-bottom":"2px solid #444"});$(this).addClass("menu_select");"contacts"==$(".menu_select").text()?($("#info").hide(),$("#reachus").hide(),$("#contacts").fadeIn()):"reach us"==$(".menu_select").text()?($("#info").hide(),$("#contacts").hide(),$("#reachus").fadeIn()):"faq"==$(".menu_select").text()&&($("#contacts").hide(),$("#reachus").hide(),
$("#info").fadeIn())});$(".menu_item").mouseover(function(){$(this).css({"border-bottom":"2px solid #444"})});$(".menu_item").mouseout(function(){$(this).hasClass("menu_select")||$(this).css({"border-bottom":"0px solid #444\t"})});$("#font-pane").bind("mousewheel",function(a){0<=a.originalEvent.wheelDelta?"support-down"!=$("#wrapper").attr("class")&&($("#wrapper").attr("class","support-down"),$("#support-pane").attr("class","support-down")):"support-up"!=$("#wrapper").attr("class")&&($("#wrapper").attr("class",
"support-up"),$("#support-pane").attr("class","support-up"))});$("[title]").mouseover(function(){$(this).data("title",$(this).attr("title"));$(this).attr("title","")}).mouseout(function(){$(this).attr("title",$(this).data("title"))});loadArt()});$("#feedback-submit").click(function(){alert("clicked submit");$.ajax({url:"/"+subDir+"/manager/feedback.php",data:{name:$("#feedback input.nameentry").text(),email:$("#feedback input.emailentry").text(),feedback:$("#feedback textarea.feedbackentry").text()},
type:"POST",success:function(a){1==a?$("#fbmessgage").text("Thank You!"):$("#fbmessgage").text("Sorry. Please try again.");$("#feedback").hide();$("#feedback").attr("class","overlayoff")}})})})(window);
